server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://47.94.240.95:3306/xilandb?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: '!@#$%15049225782'
    driver-class-name: com.mysql.jdbc.Driver
  # 配置redis
  redis:
    host: 47.102.136.35
    password: dyydyy

xilan:
  base:
    appid: wx5f2cfd0f5d5a3f1c
    secret: a5e99a999e5f498a6d414da8d73b6f84


